stages:
- .pre
- lint
- build
- deploy

generate-dynamic-content:
  stage: .pre
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: node:18-alpine3.17
  before_script:
    - npm install
  script:
    - npm run generateIntermediaryFiles
    - npm run generateTargetAudienceMaps
    - npm run generateTargetAudiencePages
    - npm run generateTokenFile
  artifacts:
    paths:
      - mkdocs/docs/config/*
      - mkdocs/docs/prompts/target_audience/*
    expire_in: 1 week

lint:
  stage: lint
  image: node:18-alpine3.17
  before_script:
    - npm install
  script:
    - npm run lint
    - npm run stylelint

build-mkdocs:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: ubuntu:latest
  needs: ['lint', 'generate-dynamic-content']
  variables:
    TZ: UTC
  before_script:
    - apt-get update
    - apt-get install -y zip
    - apt-get install -y mkdocs
    - apt-get install -y python3-pip
    - apt-get install -y python3-venv
    - python3 -m venv zeusenv
    - source zeusenv/bin/activate
    - pip3 install mkdocs-material
  script:
    - cd mkdocs
    - mkdocs build
    - zip -r site.zip site
  artifacts:
    paths:
      - mkdocs/site.zip
    expire_in: 1 week

deploy-epam-instance:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: ubuntu:latest
  needs: ['build-mkdocs']
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apt-get install -y unzip
  script:
    - cd mkdocs
    - scp site.zip "$SSH_USER"@$VM_IPADDRESS:/tmp/site.zip
    - ssh "$SSH_USER"@$VM_IPADDRESS <<'ENDSSH'
    - cd /tmp/
    - sudo unzip site.zip
    - sudo rm -r /var/www/html/*
    - sudo mv /tmp/site/* /var/www/html/
    - sudo rm site.zip
    - sudo rm site/ -r
    - sudo systemctl reload caddy
    - ENDSSH

deploy-report-portal-instance:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs: ['build-mkdocs']
  # Sensitive CI/CD variables located in the project settings.
  # variables:
  #   AWS_ACCESS_KEY_ID: sensitive_data
  #   AWS_SECRET_ACCESS_KEY: sensitive_data
  #   AWS_DEFAULT_REGION: eu-central-1
  #   CLOUDFRONT_ID: string
  #   S3_BUCKET_NAME: string
  script:
    - unzip ./mkdocs/site.zip
    - aws s3 sync ./site/ s3://$S3_BUCKET_NAME/ --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
