site_name: Zeus
use_directory_urls: false
nav:
  - Home: /
  - Features: features.md
  - Prompts:
      - Prompts: prompts/prompts.md
      - Prompt types: prompt_types.md
      - Export prompts: export.md
  - Tutorials:
      - Video tutorials: tutorials/video_tutorials.md
  - Target Audience:
      - QA Engineer: prompts/qa_engineer/qa_engineer.md
      - SDET: prompts/sdet/sdet.md
      - Business Analyst: prompts/business_analyst/business_analyst.md
      - Product Owner: prompts/product_owner/product_owner.md
      - Developer: prompts/developer/developer.md
      - Architect: prompts/architect/architect.md
      - Designer: prompts/designer/designer.md
theme:
  name: material
copyright: Made with ❤️ by EPAM&copy; Systems, Inc. All Rights Reserved. 2023&emsp;(v2.3.0)&emsp;<div class="float-end md-copyright__highlight">- Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener">Material for MkDocs</a></div><div class="float-end"><a href="https://chat.lab.epam.com/" target="_blank" rel="noopener">EPAM AI Dial</a>&emsp;</div>
extra:
  generator: false
