site_name: Zeus
use_directory_urls: false
nav:
  - Home: /
  - Create prompt: prompts/create_edit_prompt.md
  - Export prompts: export.md
  - Target audience:
      - QA Engineer: prompts/target_audience/qa_engineer.md
      - SDET: prompts/target_audience/sdet.md
      - Business Analyst: prompts/target_audience/business_analyst.md
      - Product Owner: prompts/target_audience/product_owner.md
      - Developer: prompts/target_audience/developer.md
      - Architect: prompts/target_audience/architect.md
      - Designer: prompts/target_audience/designer.md
  - Tutorials:
      - Video tutorials: tutorials/video_tutorials.md
  - Prompt types: prompt_types.md
theme:
  name: material
copyright: Made with ❤️ by EPAM&copy; Systems, Inc. All Rights Reserved. 2023&emsp;(v3.2.4)&emsp;-&emsp;<a href="/features.html">Features</a>&emsp;-&emsp;<div class="float-end md-copyright__highlight">- Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener">Material for MkDocs</a></div><div class="float-end"><a href="https://chat.lab.epam.com/" target="_blank" rel="noopener">EPAM AI Dial</a>&emsp;</div>
extra:
  generator: false
